server:
  port: 8080
  servlet:
    context-path: /customer-order/order-service

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT_ORDER}/orderdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: admin
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      database: mysql
      ddl-auto: create
      generate-ddl: true
      show-sql: true

  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  #   username: sa
  #   password:
  # h2:
  #   console:
  #     enabled: true
  #     path: /console
  # jpa:
  #   database-platform: org.hibernate.dialect.H2Dialect
  #   database: H2
  #   show-sql: true

customer:
  topic:
    name: customerTopic

order:
  topic:
    name: orderTopic

# kafka:
#   bootstrapAddress: localhost:9092
kafka:
  bootstrapAddress: ${BOOTSTRAP_SERVER}
